name: Basic CI Model Retraining

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model-basic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (with Git LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          which python
          python --version

      - name: Install dependencies
        run: pip install mlflow==2.19.0

      - name: Set MLflow Tracking URI (optional)
        run: |
          export MLFLOW_TRACKING_URI=file:./mlruns
        shell: bash

      - name: Run mlflow project
        working-directory: ./MLProject
        run: mlflow run .

      - name: Upload trained model to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: ./MLProject/mlruns/**/artifacts/model/