name: Advanced CI - Train, Commit, and Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1. Checkout Repository & LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: 2. Pull LFS Files
        run: git lfs pull

      - name: 3. Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          # Membuat dan mengaktifkan env 'fraud_detection_env' dari file
          environment-file: MLProject/conda.yaml
          activate-environment: fraud_detection_env
      
      - name: 4. Run MLflow Project and Get Run ID
        id: training_run
        shell: bash -l {0}
        working-directory: ./MLProject
        run: |
          # Jalankan training dan simpan output log ke file
          mlflow run . --experiment-name "Automated CI Training" | tee run_output.txt
          
          # Ekstrak Run ID dari log dan simpan ke GITHUB_ENV
          LATEST_RUN_ID=$(grep "run with ID" run_output.txt | awk '{print $NF}' | tr -d "'")
          echo "Discovered MLflow Run ID: $LATEST_RUN_ID"
          echo "RUN_ID=$LATEST_RUN_ID" >> $GITHUB_ENV

      - name: 5. Commit MLflow Artifacts to Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: Update mlruns artifacts after training"
          file_pattern: 'MLProject/mlruns/'

      - name: 6. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 7. Build and Push Docker Image
        # Jalankan dari root, tapi gunakan path absolut ke mlruns
        shell: bash -l {0}
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/fraud-detection-model:latest"
          echo "Building Docker image for Run ID: ${{ env.RUN_ID }}"
          
          # Perintah build-docker dalam satu baris yang benar dan kokoh
          # Menggunakan path absolut ke tracking URI untuk menghindari ambiguitas
          mlflow models build-docker \
            --model-uri "runs:/${{ env.RUN_ID }}/model" \
            --name "$IMAGE_NAME" \
            --tracking-uri "file://${{ github.workspace }}/MLProject/mlruns"
          
          echo "Pushing Docker image: $IMAGE_NAME"
          docker push "$IMAGE_NAME"