name: Basic CI Model Retraining

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model-basic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12

      - name: Run MLflow Project
        working-directory: ./MLProject
        run: mlflow run .