name: Advanced CI - Train, Commit, and Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-commit-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set up job
        run: echo "Starting the CI/CD job..."

      - name: Run actions/checkout@v4
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python 3.12
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          # Membuat dan mengaktifkan env dari file
          environment-file: MLProject/conda.yaml
          activate-environment: fraud_detection_env

      - name: Check Env
        shell: bash -l {0}
        run: |
          echo "Conda environment is ready."
          conda info --envs
          python --version

      - name: Install dependencies
        shell: bash -l {0}
        run: echo "Dependencies installed via conda.yaml."

      - name: Run mlflow project
        shell: bash -l {0}
        working-directory: ./MLProject
        run: mlflow run . --experiment-name "Automated CI Training"

      - name: Get latest MLflow run_id
        id: get_run_id
        shell: bash -l {0}
        working-directory: ./MLProject
        run: |
          # Metode paling andal: baca langsung dari file metadata terbaru
          LATEST_RUN_ID=$(cat $(ls -t mlruns/0/*/meta.yaml | head -n 1) | grep "run_id:" | awk '{print $2}')
          echo "Discovered MLflow Run ID: $LATEST_RUN_ID"
          echo "RUN_ID=$LATEST_RUN_ID" >> $GITHUB_ENV

      - name: Commit to GitHub Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: Update mlruns artifacts after training"
          file_pattern: 'MLProject/mlruns/'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Model & Push Docker Image
        shell: bash -l {0}
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/fraud-detection-model:latest"
          echo "Building Docker image for Run ID: ${{ env.RUN_ID }}"
          
          # Menggunakan path absolut ke tracking URI untuk keandalan maksimal
          TRACKING_URI="file://${{ github.workspace }}/MLProject/mlruns"
          
          # Membangun dan Mendorong Image
          mlflow models build-docker \
            --model-uri "runs:/${{ env.RUN_ID }}/model" \
            --name "$IMAGE_NAME" \
            --tracking-uri "$TRACKING_URI"
          
          echo "Pushing Docker image: $IMAGE_NAME"
          docker push "$IMAGE_NAME"

      - name: Complete job
        run: echo "Workflow completed successfully!"